config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :posts
  
  get ':name' => 'posts#user_posts', as 'user_posts'

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
	belongs_to :user

  paginates_per 3
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :posts
has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  devise_parameter_sanitizer.permit(:account_update, keys: [:username])
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(id: @comment.post_id),
        notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def user_posts
    @user = User.find_by(username: params[:name])
    @posts = @user.posts.page(params[:page])
  end
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :blog_entry, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.hidden_field :post_id, value: @post.id %>
    <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= form.label :comment_entry %>
    <%= form.text_area :comment_entry, class: 'form-control', id: :comment_comment_entry %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Comment', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <div class="row">
      <ul class='nav nav-tabs'>
        <li role='presentation'>
          <%= link_to "Posts", posts_path %>
        </li>
        <li role='presentation'>
          <%= link_to "New Post", new_post_path %>
        </li>
        <div class="pull-right">
          <% if user_signed_in? %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
          <% end %>
        </div>
      </ul>
    </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :blog_entry %>
    <%= form.text_area :blog_entry, id: :post_blog_entry, class: 'form-control' %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit 'Add Post', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/_table.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Blog entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= link_to post.user.username, user_posts_path(name: post.user.username) %></td>
        <td><%= post.blog_entry %></td>
        <td><%= link_to 'Show', post, {class: 'btn btn-info'} %></td>
        <td><%= link_to 'Edit', edit_post_path(post), {class: 'btn btn-warning'} %></td>
        <td><%= link_to 'Destroy', post, {class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' }} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<%= render 'table', posts: @posts %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= @post.title %> by <%= @post.user.username %>
  </div>
  <div class="panel-body">
    <%= @post.blog_entry %>
  </div>
  <div class="panel-footer">
    <%= link_to 'Edit', edit_post_path(@post), {class: 'btn btn-warning'} %> |
    <%= link_to 'Destroy', post_path, {class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'}} %>
  </div>
</div>

<%= link_to 'Back', posts_path, class: 'btn btn-info' %>

<div id="comments">
    <%= render 'comments/form', comment: @comment %>
    <% @post.comments.each do |comment| %>
      <p>
	       <%= @post.user.username %> said...<br />
	       <%= comment.comment_entry %>
	    </p>
    <% end %>
</div>

app/views/posts/user_posts.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<%= render 'table', posts: @posts %>

<%= paginate @posts %>